name: insight_box
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  go_router: ^13.2.4
  google_fonts: ^6.2.1
  intl: ^0.18.1
  slang: ^3.30.2
  slang_flutter: ^3.30.0
  gap: ^3.0.1
  get_it: ^7.7.0
  injectable: ^2.4.1
  flutter_bloc: ^8.1.5
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  dio: ^5.4.3+1
  hive_flutter: ^1.1.0
  flutter_secure_storage: ^9.0.0
  dartz: ^0.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner:
  flutter_gen_runner:
  slang_build_runner: ^3.30.0
  go_router_builder: ^2.5.1
  injectable_generator: ^2.6.1
  freezed: ^2.5.2
  json_serializable: ^6.8.0
  lint: ^2.3.0
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true

  # assets:
  #   - assets/images/

flutter_gen:
  integrations:
    flutter_svg: true
